name: Webmention Analytics Build

on:
  schedule: # Every day at midnight
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  workflow_dispatch: # Run workflow manually, through the Github Actions Workflow page directly

jobs:
  webmention-analytics-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs